server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Pushpak@6996
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: 3b6b7d59f6d24fd3a7bc9f3835a4ccfd3b6b7d59f6d24fd3a7bc9f3835a4ccfd
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
